<script>
  import { onMount } from 'svelte';
  import { Filter, Search, X, Code, Plus } from 'lucide-svelte';
  import DropdownMenu from '../../layout/DropdownMenu.svelte';
  import Button from '../../components/Button.svelte';
  import DynamicFieldFilter from '../items/DynamicFieldFilter.svelte';
  import Textarea from '../../components/Textarea.svelte';
  import { api } from '../../api.js';
  import { getShortcut, matchesShortcut, getShortcutDisplay } from '../../utils/keyboardShortcuts.js';
  import { searchStore } from '../../stores/searchStore.svelte.js';

  // Get QL shortcut configuration
  const qlExecuteShortcut = getShortcut('ql', 'execute');

  // Props
  let {
    autoExecuteOnChange = false,
    'onupdate-workspaces': onupdateWorkspaces,
    'onupdate-statuses': onupdateStatuses,
    'onupdate-priorities': onupdatePriorities,
    'onupdate-search': onupdateSearch,
    'onupdate-ql-mode': onupdateQlMode,
    'onexecute-ql': onexecuteQl,
    'onupdate-ql': onupdateQl,
    'onupdate-dynamic-filters': onupdateDynamicFilters,
  } = $props();

  // Derived values from store (auto-subscription via $searchStore)
  let searchQuery = $derived($searchStore.searchQuery);
  let selectedWorkspaces = $derived($searchStore.selectedWorkspaces);
  let selectedStatuses = $derived($searchStore.selectedStatuses);
  let selectedPriorities = $derived($searchStore.selectedPriorities);
  let dynamicFilters = $derived($searchStore.dynamicFilters);
  let manualQlQuery = $derived($searchStore.manualQlQuery);
  let isManualQlMode = $derived($searchStore.isManualQlMode);
  let activeQl = $derived($searchStore.activeQl);
  let showQLInput = $derived($searchStore.showQLInput);
  let qlError = $derived($searchStore.error);
  let workspaces = $derived($searchStore.workspaces);
  let storeStatuses = $derived($searchStore.allStatuses);
  let storePriorities = $derived($searchStore.allPriorities);
  let autoGeneratedQl = $derived($searchStore.autoGeneratedQl);

  // Internal state
  let workspaceDropdownItems = $state([]);
  let statusDropdownItems = $state([]);
  let priorityDropdownItems = $state([]);

  // Status and priority options
  let allStatuses = $state([]);  // Resolved from API/store
  let allPriorities = $state([]);  // Resolved from API/store

  // Load statuses and priorities from API if store hasn't populated them yet
  onMount(async () => {
    try {
      if (!storeStatuses || storeStatuses.length === 0) {
        const statuses = await api.statuses.getAll();
        allStatuses = (statuses || []).map(status => ({
          id: status.id,
          name: status.name || status.key || ''
        }));
      }

      if (!storePriorities || storePriorities.length === 0) {
        const priorities = await api.priorities.getAll();
        allPriorities = (priorities || [])
          .sort((a, b) => a.sort_order - b.sort_order)
          .map(priority => ({
            id: priority.id,
            name: priority.name,
            color: priority.color || null
          }));
      }

      buildDropdownItems();
    } catch (err) {
      console.error('Failed to load statuses and priorities:', err);
      allStatuses = [];
      allPriorities = [];
      buildDropdownItems();
    }
  });

  // Reactively update when store data changes
  $effect(() => {
    if (storeStatuses && storeStatuses.length > 0) {
      allStatuses = storeStatuses.map(status => ({
        id: status.id,
        name: status.name || status.key || ''
      }));
    }
  });

  $effect(() => {
    if (storePriorities && storePriorities.length > 0) {
      allPriorities = storePriorities.map(priority => ({
        id: priority.id,
        name: priority.name,
        color: priority.color || null
      }));
    }
  });

  // Rebuild dropdown items when data changes
  $effect(() => {
    // Access reactive dependencies to trigger re-run
    selectedWorkspaces;
    selectedStatuses;
    selectedPriorities;
    workspaces;
    allStatuses;
    allPriorities;
    buildDropdownItems();
  });

  function buildDropdownItems() {
    // Build workspace dropdown items
    workspaceDropdownItems = workspaces.map(workspace => ({
      id: workspace.id,
      type: 'checkbox',
      title: workspace.name,
      subtitle: workspace.description || `${workspace.key} workspace`,
      checked: selectedWorkspaces.includes(workspace.id),
      onChange: () => toggleWorkspace(workspace.id)
    }));

    // Build status dropdown items
    statusDropdownItems = allStatuses.map(status => ({
      id: status.id,
      type: 'checkbox',
      title: status.name,
      checked: selectedStatuses.includes(status.id),
      onChange: () => toggleStatus(status.id)
    }));

    // Build priority dropdown items
    priorityDropdownItems = allPriorities.map(priority => ({
      id: priority.id,
      type: 'checkbox',
      title: priority.name,
      checked: selectedPriorities.includes(priority.id),
      onChange: () => togglePriority(priority.id)
    }));
  }

  function toggleWorkspace(workspaceId) {
    const nextSelection = selectedWorkspaces.includes(workspaceId)
      ? selectedWorkspaces.filter(id => id !== workspaceId)
      : [...selectedWorkspaces, workspaceId];
    searchStore.setSelectedWorkspaces(nextSelection);
    onupdateWorkspaces?.(nextSelection);
    if (autoExecuteOnChange) {
      searchStore.executeSearch();
    }
  }

  function toggleStatus(status) {
    const nextSelection = selectedStatuses.includes(status)
      ? selectedStatuses.filter(s => s !== status)
      : [...selectedStatuses, status];
    searchStore.setSelectedStatuses(nextSelection);
    onupdateStatuses?.(nextSelection);
    if (autoExecuteOnChange) {
      searchStore.executeSearch();
    }
  }

  function togglePriority(priority) {
    const nextSelection = selectedPriorities.includes(priority)
      ? selectedPriorities.filter(p => p !== priority)
      : [...selectedPriorities, priority];
    searchStore.setSelectedPriorities(nextSelection);
    onupdatePriorities?.(nextSelection);
    if (autoExecuteOnChange) {
      searchStore.executeSearch();
    }
  }

  function handleSearchInput(event) {
    searchStore.setSearchQuery(event.target.value);
    onupdateSearch?.(event.target.value);
  }

  function toggleQLMode() {
    const nextMode = !showQLInput;
    searchStore.toggleQlMode();
    if (!showQLInput) {
      searchStore.exitManualQlMode();
    }
    onupdateQlMode?.(nextMode);
  }

  function executeQLQuery() {
    searchStore.executeSearch();
    searchStore.syncToURL();
    onexecuteQl?.();
    onupdateQl?.({ ql: activeQl || '', isManual: isManualQlMode });
  }

  function clearQLQuery() {
    searchStore.exitManualQlMode();
    searchStore.executeSearch();
    searchStore.syncToURL();
    onupdateQl?.({ ql: '', isManual: false });
  }

  function clearWorkspaceFilter() {
    searchStore.setSelectedWorkspaces([]);
    onupdateWorkspaces?.([]);
  }

  function clearStatusFilter() {
    searchStore.setSelectedStatuses([]);
    onupdateStatuses?.([]);
  }

  function clearPriorityFilter() {
    searchStore.setSelectedPriorities([]);
    onupdatePriorities?.([]);
  }

  function getWorkspaceName(workspaceId) {
    return workspaces.find(w => w.id === workspaceId)?.name || 'Unknown';
  }

  function handleQLInput(event) {
    searchStore.setManualQlQuery(event.target.value);
    onupdateQl?.({ ql: event.target.value, isManual: true });
  }

  function handleQLKeydown(event) {
    if (matchesShortcut(event, qlExecuteShortcut)) {
      event.preventDefault();
      executeQLQuery();
    }
  }

  function addDynamicFilter() {
    searchStore.addDynamicFilter();
    const newFilter = {
      field: null,
      operator: '=',
      value: '',
      values: []
    };
    onupdateDynamicFilters?.([...dynamicFilters, newFilter]);
  }

  function removeDynamicFilter(index) {
    searchStore.removeDynamicFilter(index);
    if (autoExecuteOnChange) {
      searchStore.executeSearch();
    }
    onupdateDynamicFilters?.(dynamicFilters.filter((_, i) => i !== index));
  }

  function handleDynamicFilterChange(index, data) {
    searchStore.updateDynamicFilter(index, data);
    if (autoExecuteOnChange) {
      searchStore.executeSearch();
    }
    const updated = [...dynamicFilters];
    updated[index] = data;
    onupdateDynamicFilters?.(updated);
  }

  function handleDynamicFilterExecute() {
    // User pressed Enter in the filter value field
    searchStore.executeSearch();
    searchStore.syncToURL();
  }
</script>

<!-- Filters Section -->
<div class="p-3 rounded border" style="background-color: var(--ds-surface-raised); border-color: var(--ds-border);">
  <div class="flex items-center justify-between mb-3">
    <div class="flex items-center gap-3">
      <h3 class="text-sm font-semibold" style="color: var(--ds-text);">Filters</h3>
      <Button
        variant="default"
        size="sm"
        icon={Code}
        onclick={toggleQLMode}
      >
        {showQLInput ? 'Hide QL' : 'Show QL'}
      </Button>
    </div>
  </div>

  <!-- QL Query Input -->
  {#if showQLInput}
    <div class="mb-4 p-3 rounded border" style="background-color: var(--ds-surface); border-color: var(--ds-border);">
      <div class="flex items-start gap-2">
        <div class="flex-1">
          <label for="ql-input" class="block text-xs font-medium mb-1" style="color: var(--ds-text);">
            Query Language
          </label>
          <Textarea
            id="ql-input"
            value={isManualQlMode ? manualQlQuery : autoGeneratedQl}
            oninput={handleQLInput}
            placeholder='Example: workspace = "My Project" AND status = "open" AND priority = "high"'
            class="font-mono"
            rows={3}
            onkeydown={handleQLKeydown}
          />
          {#if qlError}
            <div class="mt-1 text-xs font-mono" style="color: var(--ds-text-danger);">
              Error: {qlError}
            </div>
          {/if}
          <div class="mt-1 text-xs flex items-center gap-2" style="color: var(--ds-text-subtle);">
            Press {getShortcutDisplay('ql', 'execute')} to execute •
            <Button variant="link" size="sm" onclick={clearQLQuery}>Clear</Button> •
            <Button variant="link" size="sm" onclick={() => {}}>Help</Button>
          </div>
        </div>
        <div class="flex flex-col gap-1 pt-5">
          <Button
            variant="primary"
            size="sm"
            onclick={executeQLQuery}
          >
            Execute
          </Button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Query Display (when input is hidden but query exists) -->
  {#if !showQLInput && (isManualQlMode ? manualQlQuery.trim() : autoGeneratedQl.trim())}
    <div class="mb-3 p-2 rounded" style="background-color: var(--ds-accent-blue-subtler); border: 1px solid var(--ds-border);">
      <div class="flex items-center justify-between">
        <span class="text-xs font-medium" style="color: var(--ds-text);">Active Query:</span>
        <Button
          variant="link"
          size="sm"
          onclick={toggleQLMode}
        >
          Edit
        </Button>
      </div>
      <code class="font-mono text-xs block mt-1 break-all" style="color: var(--ds-accent-blue);">
        {isManualQlMode ? manualQlQuery : autoGeneratedQl}
      </code>
    </div>
  {/if}

  <div class="flex items-center gap-2 flex-wrap">
    <!-- Workspace Filter -->
    <div class="relative">
      <DropdownMenu
        triggerText={selectedWorkspaces.length === 0 ? 'Select Workspaces' : `${selectedWorkspaces.length} workspace${selectedWorkspaces.length === 1 ? '' : 's'} selected`}
        triggerIcon={Filter}
        items={workspaceDropdownItems}
        maxWidth="max-w-md"
        showChevron={true}
        triggerClass="filter-dropdown-trigger"
      />
    </div>

    <!-- Status Filter -->
    <div class="relative">
      <DropdownMenu
        triggerText={selectedStatuses.length === 0 ? 'All Statuses' : `${selectedStatuses.length} status${selectedStatuses.length === 1 ? '' : 'es'} selected`}
        triggerIcon={Filter}
        items={statusDropdownItems}
        maxWidth="max-w-sm"
        showChevron={true}
        triggerClass="filter-dropdown-trigger"
      />
    </div>

    <!-- Priority Filter -->
    <div class="relative">
      <DropdownMenu
        triggerText={selectedPriorities.length === 0 ? 'All Priorities' : `${selectedPriorities.length} priorit${selectedPriorities.length === 1 ? 'y' : 'ies'} selected`}
        triggerIcon={Filter}
        items={priorityDropdownItems}
        maxWidth="max-w-sm"
        showChevron={true}
        triggerClass="filter-dropdown-trigger"
      />
    </div>

    <!-- Search -->
    <div class="relative flex-1 max-w-md">
      <Search class="w-4 h-4 absolute left-2.5 top-1/2 transform -translate-y-1/2" style="color: var(--ds-icon-subtle);" />
      <input
        type="text"
        placeholder="Search work items..."
        value={searchQuery}
        oninput={handleSearchInput}
        class="pl-9 pr-3 py-1.5 text-sm border rounded w-full focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
        style="background-color: var(--ds-surface); border-color: var(--ds-border); color: var(--ds-text);"
      />
    </div>
  </div>

  <!-- Dynamic Filters Section -->
  <!-- Always show dynamic filters section to allow adding custom field filters -->
  <div class="mt-3 space-y-2">
    {#each dynamicFilters as filter, index}
      <DynamicFieldFilter
        {filter}
        onchange={(data) => handleDynamicFilterChange(index, data)}
        onremove={() => removeDynamicFilter(index)}
        onexecute={handleDynamicFilterExecute}
      />
    {/each}

    <!-- Always show Add Field Filter button regardless of QL mode -->
    <div>
      <Button
        variant="ghost"
        size="sm"
        icon={Plus}
        onclick={addDynamicFilter}
      >
        Add Field Filter
      </Button>
    </div>
  </div>
</div>

<style>
  :global(.filter-dropdown-trigger) {
    color: var(--ds-text);
    background-color: var(--ds-surface);
    border: 1px solid var(--ds-border);
    padding: 0.375rem 0.625rem;
    font-size: 0.875rem;
    border-radius: 0.375rem;
  }

  :global(.filter-dropdown-trigger:hover) {
    background-color: var(--ds-surface-hovered);
  }
</style>
