import { writable, derived, get } from 'svelte/store';
import { QLBuilder } from '../utils/ql.js';
import { api } from '../api.js';

/**
 * Create the centralized search/filter store
 * Manages all search state and automatically computes QL from filters
 */
function createSearchStore() {
  // ===== Base State Stores =====

  // Text search query
  const searchQuery = writable('');

  // Selected workspace IDs
  const selectedWorkspaces = writable([]);

  // Selected status names
  const selectedStatuses = writable([]);

  // Selected priority levels
  const selectedPriorities = writable([]);

  // Dynamic custom field filters
  const dynamicFilters = writable([]);

  // Manual QL query mode
  const manualQlQuery = writable('');
  const isManualQlMode = writable(false);

  // UI state
  const showQLInput = writable(false);

  // Search results
  const searchResults = writable([]);
  const loading = writable(false);
  const error = writable(null);

  // Reference data (needed for QL building)
  const workspaces = writable([]);
  const allStatuses = writable([]);
  const allPriorities = writable([]);

  // Auto-search control
  let searchTimeout = null;
  let autoSearchEnabled = true;

  // ===== Derived Stores =====

  /**
   * Auto-generated QL from UI filters
   * Recomputes whenever any filter changes
   */
  const autoGeneratedQl = derived(
    [selectedWorkspaces, selectedStatuses, selectedPriorities, searchQuery, dynamicFilters, workspaces],
    ([$selectedWorkspaces, $selectedStatuses, $selectedPriorities, $searchQuery, $dynamicFilters, $workspaces]) => {
      // Check if we have any valid dynamic filters
      const hasDynamicFilters = $dynamicFilters.length > 0 &&
        $dynamicFilters.some(f => f.field && (f.value !== '' || (f.values && f.values.length > 0)));

      // If no filters are set, return empty
      if ($selectedWorkspaces.length === 0 &&
          $selectedStatuses.length === 0 &&
          $selectedPriorities.length === 0 &&
          !$searchQuery.trim() &&
          !hasDynamicFilters) {
        return '';
      }

      // Build the QL query from current filter state
      return QLBuilder.buildQuery({
        workspaces: $selectedWorkspaces.map(id =>
          $workspaces.find(w => w.id === id)?.name
        ).filter(Boolean),
        statuses: $selectedStatuses,
        priorities: $selectedPriorities,
        search: $searchQuery,
        dynamicFields: $dynamicFilters
      });
    }
  );

  /**
   * Active QL query (either manual or auto-generated)
   * This is what gets sent to the API
   */
  const activeQl = derived(
    [isManualQlMode, manualQlQuery, autoGeneratedQl],
    ([$isManualQlMode, $manualQlQuery, $autoGeneratedQl]) => {
      return $isManualQlMode ? $manualQlQuery : $autoGeneratedQl;
    }
  );

  /**
   * Filter summary for display
   */
  const filterSummary = derived(
    [selectedWorkspaces, selectedStatuses, selectedPriorities, searchQuery, dynamicFilters, workspaces, allPriorities, allStatuses],
    ([$selectedWorkspaces, $selectedStatuses, $selectedPriorities, $searchQuery, $dynamicFilters, $workspaces, $allPriorities, $allStatuses]) => {
      const parts = [];

      if ($selectedWorkspaces.length > 0) {
        const names = $selectedWorkspaces
          .map(id => $workspaces.find(w => w.id === id)?.name)
          .filter(Boolean)
          .join(', ');
        if (names) parts.push(`Workspaces: ${names}`);
      }

      if ($selectedStatuses.length > 0) {
        const statusNames = $selectedStatuses
          .map(id => $allStatuses.find(s => s.id === id)?.name || id)
          .filter(Boolean)
          .join(', ');
        parts.push(`Status: ${statusNames}`);
      }

      if ($selectedPriorities.length > 0) {
        const priorityNames = $selectedPriorities
          .map(id => $allPriorities.find(p => p.id === id)?.name || id)
          .filter(Boolean)
          .join(', ');
        parts.push(`Priority: ${priorityNames}`);
      }

      if ($searchQuery.trim()) {
        parts.push(`Search: "${$searchQuery}"`);
      }

      if ($dynamicFilters.length > 0) {
        const validFilters = $dynamicFilters.filter(f =>
          f.field && (f.value !== '' || (f.values && f.values.length > 0))
        );
        if (validFilters.length > 0) {
          parts.push(`${validFilters.length} custom filter(s)`);
        }
      }

      return parts.join(' • ');
    }
  );

  /**
   * Has any active filters
   */
  const hasFilters = derived(
    [selectedWorkspaces, selectedStatuses, selectedPriorities, searchQuery, dynamicFilters],
    ([$selectedWorkspaces, $selectedStatuses, $selectedPriorities, $searchQuery, $dynamicFilters]) => {
      const hasDynamicFilters = $dynamicFilters.length > 0 &&
        $dynamicFilters.some(f => f.field && (f.value !== '' || (f.values && f.values.length > 0)));

      return $selectedWorkspaces.length > 0 ||
        $selectedStatuses.length > 0 ||
        $selectedPriorities.length > 0 ||
        $searchQuery.trim().length > 0 ||
        hasDynamicFilters;
    }
  );

  /**
   * Combined state for easy subscription
   */
  const combined = derived(
    [
      searchQuery,
      selectedWorkspaces,
      selectedStatuses,
      selectedPriorities,
      dynamicFilters,
      manualQlQuery,
      isManualQlMode,
      showQLInput,
      searchResults,
      loading,
      error,
      workspaces,
      allStatuses,
      allPriorities,
      autoGeneratedQl,
      activeQl,
      filterSummary,
      hasFilters
    ],
    ([
      $searchQuery,
      $selectedWorkspaces,
      $selectedStatuses,
      $selectedPriorities,
      $dynamicFilters,
      $manualQlQuery,
      $isManualQlMode,
      $showQLInput,
      $searchResults,
      $loading,
      $error,
      $workspaces,
      $allStatuses,
      $allPriorities,
      $autoGeneratedQl,
      $activeQl,
      $filterSummary,
      $hasFilters
    ]) => ({
      // Filter state
      searchQuery: $searchQuery,
      selectedWorkspaces: $selectedWorkspaces,
      selectedStatuses: $selectedStatuses,
      selectedPriorities: $selectedPriorities,
      dynamicFilters: $dynamicFilters,

      // QL state
      manualQlQuery: $manualQlQuery,
      isManualQlMode: $isManualQlMode,
      autoGeneratedQl: $autoGeneratedQl,
      activeQl: $activeQl,

      // UI state
      showQLInput: $showQLInput,

      // Results
      searchResults: $searchResults,
      loading: $loading,
      error: $error,

      // Reference data
      workspaces: $workspaces,
      allStatuses: $allStatuses,
      allPriorities: $allPriorities,

      // Computed
      filterSummary: $filterSummary,
      hasFilters: $hasFilters
    })
  );

  // ===== Search Execution =====

  async function executeSearch() {
    const currentActiveQl = get(activeQl);
    const currentHasFilters = get(hasFilters);
    const currentIsManualQlMode = get(isManualQlMode);
    const currentManualQlQuery = get(manualQlQuery);

    // Check if we have any criteria
    if (!currentActiveQl.trim() && !currentHasFilters && !(currentIsManualQlMode && currentManualQlQuery.trim())) {
      searchResults.set([]);
      return;
    }

    loading.set(true);
    error.set(null);

    try {
      const searchParams = {};

      // Add the QL query if we have one
      if (currentActiveQl.trim()) {
        searchParams.ql = currentActiveQl;
      }

      // Set a reasonable limit
      searchParams.limit = 100;

      const response = await api.items.getAll(searchParams);
      searchResults.set(response.items || []);
    } catch (err) {
      console.error('Search failed:', err);
      error.set(err.message || 'Search failed');
      searchResults.set([]);
    } finally {
      loading.set(false);
    }
  }

  // Debounced search execution
  function debouncedSearch() {
    if (!autoSearchEnabled) return;

    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(async () => {
      await executeSearch();
      syncStateToURL();
    }, 300);
  }

  // Watch for filter changes and trigger search
  // Subscribe to filter changes to trigger auto-search
  const unsubscribeFilters = derived(
    [selectedWorkspaces, selectedStatuses, selectedPriorities, searchQuery, dynamicFilters],
    () => {
      // Only trigger search if not in manual mode
      if (!get(isManualQlMode)) {
        debouncedSearch();
      }
    }
  ).subscribe(() => {});

  // ===== Public API =====

  function syncStateToURL() {
    const url = new URL(window.location);
    const state = get(combined);

    // Clear all search params first
    const searchKeys = ['ql', 'workspaces', 'statuses', 'priorities', 'search', 'dynamicFilters', 'showQL'];
    searchKeys.forEach(key => url.searchParams.delete(key));

    // Add params based on current state
    if (state.isManualQlMode && state.manualQlQuery.trim()) {
      url.searchParams.set('ql', state.manualQlQuery);
    }

    if (state.selectedWorkspaces.length > 0) {
      url.searchParams.set('workspaces', state.selectedWorkspaces.join(','));
    }

    if (state.selectedStatuses.length > 0) {
      url.searchParams.set('statuses', state.selectedStatuses.join(','));
    }

    if (state.selectedPriorities.length > 0) {
      url.searchParams.set('priorities', state.selectedPriorities.join(','));
    }

    if (state.searchQuery.trim()) {
      url.searchParams.set('search', state.searchQuery);
    }

    if (state.dynamicFilters.length > 0) {
      const filtersToSerialize = state.dynamicFilters.filter(f =>
        f.field && (f.value !== '' || (f.values && f.values.length > 0))
      );
      if (filtersToSerialize.length > 0) {
        url.searchParams.set('dynamicFilters', JSON.stringify(filtersToSerialize));
      }
    }

    if (state.showQLInput) {
      url.searchParams.set('showQL', 'true');
    }

    window.history.pushState({}, '', url);
  }

  return {
    subscribe: combined.subscribe,

    // ===== Filter Mutations =====

    setSearchQuery(query) {
      searchQuery.set(query);
    },

    setSelectedWorkspaces(workspaceIds) {
      selectedWorkspaces.set(workspaceIds);
    },

    toggleWorkspace(workspaceId) {
      selectedWorkspaces.update(current => {
        if (current.includes(workspaceId)) {
          return current.filter(id => id !== workspaceId);
        }
        return [...current, workspaceId];
      });
    },

    setSelectedStatuses(statuses) {
      selectedStatuses.set(statuses);
    },

    toggleStatus(status) {
      selectedStatuses.update(current => {
        if (current.includes(status)) {
          return current.filter(s => s !== status);
        }
        return [...current, status];
      });
    },

    setSelectedPriorities(priorities) {
      selectedPriorities.set(priorities);
    },

    setDynamicFilters(filters) {
      dynamicFilters.set(filters);
    },

    togglePriority(priority) {
      selectedPriorities.update(current => {
        if (current.includes(priority)) {
          return current.filter(p => p !== priority);
        }
        return [...current, priority];
      });
    },

    setDynamicFilters(filters) {
      dynamicFilters.set(filters);
    },

    addDynamicFilter() {
      dynamicFilters.update(current => [
        ...current,
        {
          field: null,
          operator: '=',
          value: '',
          values: []
        }
      ]);
    },

    updateDynamicFilter(index, filter) {
      dynamicFilters.update(current => {
        const updated = [...current];
        updated[index] = filter;
        return updated;
      });
    },

    removeDynamicFilter(index) {
      dynamicFilters.update(current =>
        current.filter((_, i) => i !== index)
      );
    },

    // ===== QL Mode =====

    setManualQlQuery(query) {
      manualQlQuery.set(query);
      isManualQlMode.set(true);
    },

    toggleQlMode() {
      showQLInput.update(current => !current);
    },

    setShowQLInput(show) {
      showQLInput.set(show);
    },

    exitManualQlMode() {
      isManualQlMode.set(false);
      manualQlQuery.set('');
    },

    // ===== Clear Functions =====

    clearFilters() {
      searchQuery.set('');
      selectedWorkspaces.set([]);
      selectedStatuses.set([]);
      selectedPriorities.set([]);
      dynamicFilters.set([]);
      manualQlQuery.set('');
      isManualQlMode.set(false);
      error.set(null);
    },

    clearResults() {
      searchResults.set([]);
      error.set(null);
    },

    // ===== Search Control =====

    executeSearch,

    setAutoSearch(enabled) {
      autoSearchEnabled = enabled;
    },

    // ===== Reference Data =====

    async loadReferenceData() {
      try {
        const [workspacesData, statusesData, prioritiesData] = await Promise.all([
          api.workspaces.getAll(),
          api.statuses.getAll(),
          api.priorities.getAll()
        ]);

        workspaces.set(workspacesData || []);
        allStatuses.set(statusesData || []);
        allPriorities.set(prioritiesData || []);
      } catch (err) {
        console.error('Failed to load reference data:', err);
      }
    },

    setWorkspaces(data) {
      workspaces.set(data);
    },

    setStatuses(data) {
      allStatuses.set(data);
    },

    setPriorities(data) {
      allPriorities.set(data);
    },

    // ===== URL Sync =====

    syncToURL() {
      syncStateToURL();
    },

    restoreFromURL() {
      const urlParams = new URLSearchParams(window.location.search);

      // Temporarily disable auto-search while restoring
      autoSearchEnabled = false;

      // Restore QL query
      const urlQL = urlParams.get('ql');
      if (urlQL) {
        manualQlQuery.set(urlQL);
        isManualQlMode.set(true);
      }

      // Restore workspaces
      const urlWorkspaces = urlParams.get('workspaces');
      if (urlWorkspaces) {
        const workspaceIds = urlWorkspaces.split(',')
          .map(id => parseInt(id, 10))
          .filter(id => !isNaN(id));
        selectedWorkspaces.set(workspaceIds);
      }

      // Restore statuses
      const urlStatuses = urlParams.get('statuses');
      if (urlStatuses) {
        const statusIds = urlStatuses.split(',')
          .map(value => {
            const parsedId = parseInt(value, 10);
            if (!isNaN(parsedId)) return parsedId;
            const matchingStatus = get(allStatuses).find(status =>
              (status.name || status.key || '').toLowerCase() === value.toLowerCase()
            );
            return matchingStatus ? matchingStatus.id : null;
          })
          .filter(id => id !== null && id !== undefined);
        selectedStatuses.set(statusIds);
      }

      // Restore priorities
      const urlPriorities = urlParams.get('priorities');
      if (urlPriorities) {
        const priorityIds = urlPriorities.split(',')
          .map(value => {
            const parsedId = parseInt(value, 10);
            if (!isNaN(parsedId)) return parsedId;
            const matchingPriority = get(allPriorities).find(priority =>
              priority.name?.toLowerCase() === value.toLowerCase()
            );
            return matchingPriority ? matchingPriority.id : null;
          })
          .filter(id => !isNaN(id) && id !== null);
        selectedPriorities.set(priorityIds);
      }

      // Restore search query
      const urlSearch = urlParams.get('search');
      if (urlSearch) {
        searchQuery.set(urlSearch);
      }

      // Restore dynamic filters
      const urlDynamicFilters = urlParams.get('dynamicFilters');
      if (urlDynamicFilters) {
        try {
          dynamicFilters.set(JSON.parse(urlDynamicFilters));
        } catch (err) {
          console.error('Failed to parse dynamic filters from URL:', err);
        }
      }

      // Restore QL input visibility
      const urlShowQL = urlParams.get('showQL');
      if (urlShowQL === 'true') {
        showQLInput.set(true);
      }

      // Re-enable auto-search
      autoSearchEnabled = true;
    },

    // ===== Direct State Setters (for external components like Collections) =====

    setSearchResults(results) {
      searchResults.set(results || []);
    },

    setLoading(isLoading) {
      loading.set(isLoading);
    },

    setError(errorMsg) {
      error.set(errorMsg);
    },

    // ===== Cleanup =====

    destroy() {
      clearTimeout(searchTimeout);
      unsubscribeFilters();
    }
  };
}

export const searchStore = createSearchStore();
